# Generated by Django 3.1.6 on 2021-04-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('patient', 'PATIENT'), ('medecin', 'MEDECIN')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spécialité',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('age', models.IntegerField(null=True)),
                ('Compte', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.compte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('local', models.CharField(max_length=200, null=True)),
                ('numero_tel', models.CharField(max_length=200, null=True)),
                ('prix_visite', models.FloatField(null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('profil_img', models.ImageField(blank=True, default='profil1.jpg', null=True, upload_to='')),
                ('Compte', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.compte')),
                ('Spécialité', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.spécialité')),
                ('Ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.ville')),
            ],
            options={
                'unique_together': {('nom',)},
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.medecin')),
                ('Patient', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.patient')),
            ],
        ),
    ]
