# Generated by Django 3.1.6 on 2021-04-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_commentaire_compte_medecin_patient_spécialité_utilisateur_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='Compte',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.compte'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Compte',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.compte'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
