# Generated by Django 3.1.6 on 2021-04-19 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0005_auto_20210419_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='Compte',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Compte',
        ),
        migrations.AddField(
            model_name='medecin',
            name='roles',
            field=models.CharField(choices=[('patient', 'PATIENT'), ('medecin', 'MEDECIN')], default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='roles',
            field=models.CharField(choices=[('patient', 'PATIENT'), ('medecin', 'MEDECIN')], default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
