# Generated by Django 3.1.6 on 2021-04-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0011_auto_20210421_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('patient', 'PATIENT'), ('medecin', 'MEDECIN')], default=True, max_length=10),
        ),
    ]
