# Generated by Django 3.1.6 on 2021-04-21 00:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0012_auto_20210421_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Compte',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='Profile',
            new_name='Compte',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Profile',
            new_name='Compte',
        ),
    ]
