# Generated by Django 3.1.6 on 2021-04-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0013_auto_20210421_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='Patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classification.patient'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='roles',
            field=models.CharField(choices=[('patient', 'PATIENT'), ('medecin', 'MEDECIN')], default=None, max_length=10),
        ),
    ]
