# Generated by Django 3.1.6 on 2021-04-24 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0014_auto_20210423_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100, null=True)),
                ('Compte', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.compte')),
            ],
        ),
    ]
