# Generated by Django 3.1.6 on 2021-04-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0017_auto_20210424_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Compte',
        ),
    ]
