# Generated by Django 3.1.6 on 2021-04-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0020_auto_20210425_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Compte',
        ),
    ]
