# Generated by Django 3.1.6 on 2021-04-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0024_auto_20210426_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
