# Generated by Django 3.1.6 on 2021-04-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0025_medecin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-Mal'), (2, "2-D'accord"), (3, '3-Bien'), (4, '4-Très bien'), (5, '5-Parfait')]),
        ),
    ]
