# Generated by Django 3.1.6 on 2021-05-01 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0027_auto_20210501_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('patient', 'PATIENT'), ('medecin', 'MEDECIN')], default=None, max_length=10)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='Compte',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.compte'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Compte',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.compte'),
        ),
    ]
