# Generated by Django 3.1.6 on 2021-05-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0029_auto_20210502_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='Compte',
            new_name='compte',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Compte',
            new_name='compte',
        ),
        migrations.AlterField(
            model_name='compte',
            name='roles',
            field=models.CharField(choices=[('P', 'PATIENT'), ('M', 'MEDECIN')], default=None, max_length=10),
        ),
    ]
