# Generated by Django 3.1.6 on 2021-05-08 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0031_auto_20210507_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='patient',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='compte',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.compte'),
        ),
    ]
