# Generated by Django 3.1.6 on 2021-05-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0032_auto_20210508_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='compte',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='patient',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classification.patient'),
        ),
    ]
