# Generated by Django 3.1.6 on 2021-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0033_auto_20210520_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.PositiveSmallIntegerField(choices=[(6, 'bien'), (7, 'très bien'), (8, 'm3alem')])),
                ('negative', models.PositiveSmallIntegerField(choices=[(1, '5ayeb'), (2, 'mal'), (3, 'metwaset')])),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='note',
            field=models.FloatField(null=True),
        ),
    ]
