# Generated by Django 3.1.6 on 2021-05-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0034_auto_20210522_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
