# Generated by Django 3.1.6 on 2021-05-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0035_auto_20210522_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='profil_img',
        ),
        migrations.AlterField(
            model_name='medecin',
            name='note',
            field=models.FloatField(default=0, null=True),
        ),
    ]
