# Generated by Django 3.1.6 on 2021-05-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0036_auto_20210525_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dictionnaire',
        ),
    ]
