# Generated by Django 3.1.6 on 2021-05-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0038_commentaire_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='note',
            field=models.FloatField(default=True, null=True),
        ),
    ]
